[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = ""
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'dist/js'
    target = 'assets/js/modules/popup'
    include = '*.js'
  [[module.mounts]]
    source = 'static'
    target = 'static'

[params.modules.popup]
  integration = "critical"
  debug = false