baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-popup'

[markup.goldmark.renderer]
unsafe = true

[module]
  # Build and serve using local mod-popup clone declared in the named Hugo workspace:
  workspace = "mod-popup.work"
  replacements = "github.com/anoduck/mod-popup --> ../.."

  [[module.imports]]
    path = "github.com/anoduck/mod-popup"
  [[module.imports.mounts]]
    source = 'static'
    target = 'static'
  [[module.imports.mounts]]
    source = 'dist/js/popup.js'
    target = 'static/js/popup.js'
  [[module.imports.mounts]]
    source = 'dist/scss/popup.scss'
    target = 'static/popup.css'
  [[module.imports.mounts]]
    source = 'layouts'
    target = 'layouts'