baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-construction'

[module]
  # Build and serve using local mod-construction clone declared in the named Hugo workspace:
  workspace = "mod-popup.work"
  [[module.imports]]
    path = "github.com/anoduck/mod-popup"
  [[module.imports.mounts]]
    source = "dist"
    target = "static"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"